include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/localization/**"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
